### ISSUE TITLE
pre_annotation_scripts

### ISSUE THREAD

**Issue by MekWarrior** [vanvalenlab/deepcell-toolbox#11]
- contrast_adjustment.py is tricky to work with because of the inputs it requires, especially with channels (not all of our datasets have more than one channel)
- There are two montage maker scripts in that folder and I'm not sure which one we want to go with
- File structure and clarity of prompts are issues there as well

**Comment by icejannie** [comment]
In process of adding it to Pre-Annotation notebook and changing prompts/file structure. Will  eventually add widgets to notebook/application for user to redefine/add additional filters if standard contrast adjustment did not go as desired (shown using one data file).

**Comment by MekWarrior** [comment]
Resolved with #19
