### ISSUE TITLE
fill_holes is unusably slow for large images

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-toolbox#113]
**Is your feature request related to a problem? Please describe.**
Part of the Mesmer post-processing involves 1) removing very small predicted objects and then 2) filling any holes contained within the remaining predicted objects. However, the `fill_holes` function scales very poorly with image size. For small images (512x512), it's around 30% of the post-processing time, but for large images it quickly approaches 99% of the total time. There are two problems with the function:

1) It contains a for loop over all identified holes, which is slow
2) For each identified hole, it creates a binary mask to manipulate. This mask is the same size as the original image, so as the image size increases, so does the mask size, leading to very poor performance

I've copied the function below. 

```
def fill_holes(label_img, size=10, connectivity=1):
    """Fills holes located completely within a given label with pixels of the same value
    Args:
        label_img: a 2D labeled image
        size: maximum size for a hole to be filled in
        connectivity: the connectivity used to define the hole
    Returns:
        label_img_filled: a labeled image with small holes filled in with same value as the label
    """

    label_img_filled = copy(label_img)

    # invert the image, so that holes are objects
    inverse_img = np.logical_not(label_img)

    inverse_img_removed = remove_small_objects(ar=inverse_img, min_size=size,
                                               connectivity=connectivity)

    # identify potential holes in the image
    potential_holes = inverse_img != inverse_img_removed
    potential_holes = label(potential_holes)

    # for each identified hole, check if it is contained completely within a single label
    for i in np.unique(potential_holes):
        mask = potential_holes == i
        enlarged_mask = dilation(mask, selem=square(3))

        label_values = np.unique(label_img[enlarged_mask])
        label_values = [x for x in label_values if x != 0]

        # the enlarged mask only contains a single value, hence the hole is completely contained
        # within a single label
        if len(label_values) == 1:
            label_img_filled[mask] = label_values[0]

    return label_img_filled
```

**Describe the solution you'd like**
I see two potential solutions. The first would be to check the input image size to application, and if it's above a certain threshold, raise a warning to the user that they should turn off file holes. @oldridge, you can manually override this right now when you call predict to set fill_holes=0, you should be able to process your large images. This would be easy to do, but would result in slightly worse segmentation predictions. 

The second would be to optimize this function to work better. We could use coordinate indexing from regionprops instead of mask indexing for a massive speedup. However, I'm not sure if there's a good way to substitute the mask in the "enlarge" step? Any suggestions here would be welcome.

**Comment by willgraf** [comment]
Did we ever look into [`skimage.morphology.remove_small_holes`](https://scikit-image.org/docs/dev/api/skimage.morphology.html#skimage.morphology.remove_small_holes)

**Comment by vanvalen** [comment]
I did - it causes one of the tests to fail.

**Comment by willgraf** [comment]
I took a stab at re-implementing the function using `remove_small_holes`. Unfortunately, it looks like it requires a binary input image? I'm still tooling a bit - IDK if O(labels) is any faster than O(holes), but I think there's less computation in each loop.

```python
def fill_holes(label_img, size=10, connectivity=1):
    """Fills holes located completely within a given label with pixels of the same value

    Args:
        label_img (numpy.array): a 2D labeled image
        size (int): maximum size for a hole to be filled in
        connectivity (int): the connectivity used to define the hole

    Returns:
        numpy.array: a labeled image with no holes smaller than ``size``
            contained within any label.
    """
    output_image = np.copy(label_img)
    labels = np.unique(label_img)
    for l in labels:
        if l != 0:  # skip background

            filled = remove_small_holes(
                ar=(label_img == l).astype('int'),
                area_threshold=size,
                connectivity=connectivity)

            output_image = np.where(filled, l, output_image)

    return output_image
```

**Comment by ngreenwald** [comment]
![image](https://user-images.githubusercontent.com/13770365/129398654-3adf929f-f363-4b77-bb24-9ccae491f9d3.png)
The test that's failing is kind of a corner case I put in there. If this is significantly faster, I think it's worth the tradeoff. We could also do the same thing we do for peak_local_max, give the user the option of which to specify. 

I'm happy to do some performance testing and see if it makes a difference, I'm guessing it will

**Comment by ngreenwald** [comment]
Will, the one you posted above is not significantly faster. `skimage.morphology.remove_small_holes` is about 300x faster, which is great, and would solve the issue. However, it returns a binary mask, meaning any distinct cells which are touching are joined together. So we'd need to enforce no touching between adjacent cells, which is a deal breaker for tissue images. 

If we supplied a mask containing just the cell of interest which has a hole, we could use the skimage function to fill it, but it won't work on the entire image at once. We could potentially use regionprops to identify the cells which contain a hole, get their binary mask, fill in the mask, and then replace the mask in the larger image. However, I'm not sure if that will be significantly faster.

**Comment by ngreenwald** [comment]
Dave's function works for holes which are completely contained within a cell, but leads to weird results at the border: 
![image](https://user-images.githubusercontent.com/13770365/129409926-ff4bcffe-16ea-482b-a61d-963c340ac5c6.png)

**Comment by willgraf** [comment]
I've got an implementation for the regionprops version passing tests. Could you please help me benchmark it?

```python
def fill_holes(label_img, size=10, connectivity=1):
    """Fills holes located completely within a given label with pixels of the same value

    Args:
        label_img (numpy.array): a 2D labeled image
        size (int): maximum size for a hole to be filled in
        connectivity (int): the connectivity used to define the hole

    Returns:
        numpy.array: a labeled image with no holes smaller than ``size``
            contained within any label.
    """
    output_image = np.copy(label_img)

    props = regionprops(np.squeeze(label_img.astype('int')), cache=False)
    for prop in props:
        x1, y1, x2, y2 = prop.bbox
        # widen box to make sure there is boundary
        x1 = x1 // 2
        x2 = x2 * 2
        y1 = y1 // 2
        y2 = y2 * 2
        patch = output_image[x1:x2, y1:y2]

        filled = remove_small_holes(
            ar=(patch == prop.label).astype('int'),
            area_threshold=size,
            connectivity=connectivity)

        output_image[x1:x2, y1:y2] = np.where(filled, prop.label, patch)

    return output_image
```

**Comment by ngreenwald** [comment]
Yup, will do

**Comment by geneva-miller** [comment]
I'm also curious about this indexing:
```python
        x1, y1, x2, y2 = prop.bbox
        # widen box to make sure there is boundary
        w, h = (x2 - x1) // 2, (y2 - y1) // 2
        x1 = max(x1 - w, 0)
        x2 = min(x2 + w, output_image.shape[0])
        y1 = max(y1 - h, 0)
        y2 = min(y2 + h, output_image.shape[1])
        patch = output_image[x1:x2, y1:y2]
```
Why is there so much boundary needed around each object? I'm wondering if we couldn't just use the `slice` property of `regionprops`, eg
```python
        location = prop.slice
        patch = output_image[location]
```

**Comment by willgraf** [comment]
I was unaware of `prop.slice`! It's much cleaner and, with the Euler number addition, it passes all tests.

`remove_small_holes` was filling in holes that shouldn't be filled in when the window was just the bounding box. Widening the bounding box was a workaround to prevent those holes from filling.

It turns out the Euler number also resolves that workaround!

**Comment by willgraf** [comment]
I've written a brief benchmarking script to test this:

```python
import timeit
import skimage
from deepcell_toolbox.utils import fill_holes

def get_dummy_data(length=2000):
    _ = timeit.default_timer()
    x = skimage.data.binary_blobs(
        length=length, blob_size_fraction=.005,
        n_dim=2, volume_fraction=0.95, seed=1)
    x = skimage.measure.label(x)
    props = skimage.measure.regionprops(x.astype('int'), cache=False)
    for prop in props:
        # put a hole in every object's centroid
        x[tuple([int(c) for c in prop.centroid])] = 0
    print('built dummy data in {}s'.format(timeit.default_timer() - _))
    return x

sizes = [100, 1000, 10000]
for size in sizes:
    img = get_dummy_data(size)
    start = timeit.default_timer()
    filled = fill_holes(img)
    print('filled holes in {0}x{0} image: {1}s'.format(
        size, timeit.default_timer() - start))
```

The results: the above `regionprops` draft is is MUCH faster 🔥 

master branch benchmarking results:

```
>>> python test.py    
built dummy data in 0.0033330569999999726s
filled holes in 100x100 image: 0.02825278599999992s
built dummy data in 0.07209437600000002s
filled holes in 1000x1000 image: 19.659712939s
built dummy data in 20.895734451000003s
^C after 10 minutes...
```

This draft results:

```
>>> python test.py
built dummy data in 0.003363463000000011s
filled holes in 100x100 image: 0.0011318570000000694s
built dummy data in 0.07137025799999996s
filled holes in 1000x1000 image: 0.03744884100000001s
built dummy data in 19.19052976s
filled holes in 10000x10000 image: 6.101829598999998s
```

For good measure I also benchmarked ONLY doing the remove_small_holes function (as in bb050b2e4d8a00d0c73d91aac7cad1df46108a89):

```
>>> python test.py
built dummy data in 0.0033501940000000285s
filled holes in 100x100 image: 0.0019482189999999733s
built dummy data in 0.07367515400000002s
filled holes in 1000x1000 image: 0.10184406000000001s
built dummy data in 19.823306438000003s
filled holes in 10000x10000 image: 13.602379407999997s
```

The `regionprops` build is still faster! and it does not sacrifice any filling inaccuracies.

@ngreenwald can you please update #114 with what is in the comment above and request a review from me?
