### ISSUE TITLE
Typo in summary stats from metrics

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-toolbox#124]
The object-based summary stats have a typo where recall is not multiplied by 100 prior to converting from a decimal to a percent
![image](https://user-images.githubusercontent.com/13770365/166485761-38cc0671-f88c-4eb9-9376-3b1c0b8f998c.png)

**Comment by msschwartz21** [comment]
I thought we fixed this in #118, but maybe we only made the change to the stats that are returned in the summary dictionary, not the printed version.

**Comment by ngreenwald** [comment]
You're right, the model registry is using 0.10.2
