### ISSUE TITLE
How I can use the Deepcell Toolbox for pre-and post-processing?

### ISSUE THREAD

**Issue by Ati-74** [vanvalenlab/deepcell-toolbox#126]
Hello.
I hope you are doing well.
Could you please let me know how I can use the Deepcell Toolbox for pre-and post-processing?
After segmenting and tracking microscopy images, what features can I extract using this tool?

**Comment by msschwartz21** [comment]
Hi Atiyeh, I don't think the toolbox has the type of functions you are looking for. It provides functions that we use in our pipelines for converting intermediate model predictions into segmentation masks, but it does not have functions that take masks and extract features that describe each object.

**Comment by Ati-74** [comment]
So okay would you please let me know that I understand perfectly correct : with using Deepcell I can’t fetch data like major axis length of each bacterium in each time step, birth length of each bacterium and so on?

**Comment by msschwartz21** [comment]
No you cannot.
