### ISSUE TITLE
tile_image doesn't check for loss of precision from dtype switching

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-toolbox#13]
We added the option to specify a different dtype output in tile image, but if it isn't specified, it will convert floats to int (and thus to 0) without raising a warning. 

We should check if this is happening and raise a warning/error if so.

**Comment by msschwartz21** [comment]
Instead of defaulting to the dtype from the original input to tiling, can we instead just use the dtype of the input to untiling?

**Comment by msschwartz21** [comment]
If we make a revision to the tile functions, let's add additional tests for rectangular images. Currently we only test on square and I have found rectangular images to be a common failure mode for these types of functions.

**Comment by willgraf** [comment]
I'm adding some more thorough tests to `tile_image` but we do not pass any `dtype` to it. `tile_image` preserves the dtype of the original data.

In `untile_image` we added an optional `dtype` parameter. If this new parameter is causing errors or unexpected behavior, I think we should remove the functionality. If a user wants to set the output image to a new dtype, they can do so themselves with numpy.

**Comment by ngreenwald** [comment]
Yeah, the reason we added the ability to specify `dtype` to `untile` was because the default behavior was to use the `dtype` of the input to `tile`. 

If we switch the behavior such that `untile` creates images with the same `dtype` as the input to `untile`, rather than the `dtype` of the input to `tile`, that addresses the issue we were having that caused us to add the manual `dtype` parameter in the first place.
