### ISSUE TITLE
using the tool to prepare Ground truths for microscopic images 

### ISSUE THREAD

**Issue by hinatanvir** [vanvalenlab/deepcell-toolbox#139]
how to use this tool to generate ground truths for the task of nuclei segmentation of microscopic images slides. I have point annotation of nucleus for each image. how those annotations can be used to generate a ground truth mask for nuclei in the image?

**Comment by msschwartz21** [comment]
Hi @hinatanvir! Thank you for your interest in `deepcell-toolbox`, but we do not have any functions to convert point annotations into segmentation masks.

**Comment by rossbar** [comment]
Thanks for the quick response @msschwartz21 . It looks like the question has been sufficiently addressed so I will close this.
