### ISSUE TITLE
Move metrics to toolbox?

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-toolbox#16]
Do you guys think it makes sense to move the metics functionality in deepcell-tf to the toolbox?

I want to import it for our analysis pipeline, and the toolbox is much more lightweight than deepcell itself. 

If there's a particular reason this wouldn't be a good idea I can obviously just import deepcell instead. Not sure exactly what the scope of the toolbox is going to be.

**Comment by willgraf** [comment]
I'm open to this idea, especially as "metrics" have always seemed like they would be a subclass of `keras.metrics`.

It looks like it would be fairly easy to move over, just need to remove the `tf_logging` import and change the `compute_overlap` from a deepcell import to `keras_retinanet` import.

**Comment by msschwartz21** [comment]
This make sense to me too.
