### ISSUE TITLE
rescale_intensity in processing.phase_preprocess returns a mostly black image

### ISSUE THREAD

**Issue by msschwartz21** [vanvalenlab/deepcell-toolbox#23]
https://github.com/vanvalenlab/deepcell-toolbox/blob/c9b1399f23fdf15460a7392951255d1b6957ab57/deepcell_toolbox/processing.py#L68

`out_range='float'` seems to be the problem. The resulting image has only two unique values (0, 1) and appears essentially black. 

We should change `out_range` to the appropriate setting and the function could also be upgrading by specifying an input shape requirement and checking for it.

**Comment by msschwartz21** [comment]
@vanvalen do you know what the correct setting is for `rescale_intensity`?

**Comment by msschwartz21** [comment]
This particular failure mode seems to be specific to `uint16` inputs. Casting to `float32` solves the problem.

@willgraf What do you think is the best way to handle this going forward? Should we convert images or raise an error in this function? Or alternatively convert the input in `deepcell.applications`?

**Comment by willgraf** [comment]
I think users would be confused if they get a different dtype returned from this function. If we cast to `float32` can we cast back to `uint16`?

Is it really only for `uint16`? What about `uint8` or `int16`?

**Comment by msschwartz21** [comment]
It seems to cause a problem for any int related datatype. And unfortunately it seems like casting back to int using `astype` doesn't work in some cases. 

What are our cytoplasm models ultimately expecting?  Do we need the data to end up between 0 and 1 as far as the model is concerned?

**Comment by willgraf** [comment]
@vanvalen Do you know if there are any requirements on the data input to the cytoplasm models?

Looking at the [source for `rescale_intensity`](https://scikit-image.org/docs/dev/api/skimage.exposure.html#skimage.exposure.rescale_intensity), it looks like the `out_range='float'` call will resize between (-1, 1).

However, if the `image.dtype` is an integer dtype, we can pass that in as our `out_range`. It looks to support the following dtypes:

```
int8 (-128, 127)
uint8 (0, 255)
int16 (-32768, 32767)
uint16 (0, 65535)
int32 (-2147483648, 2147483647)
uint32 (0, 4294967295)
int64 (-9223372036854775808, 9223372036854775807)
uint64 (0, 18446744073709551615)
longlong (-9223372036854775808, 9223372036854775807)
ulonglong (0, 18446744073709551615)
```

**Comment by willgraf** [comment]
OK after discussing, we can just cast as float 32 and rescale. Returning a different `dtype` is not perfect, but since this function is so specific we can move forward with it.
