### ISSUE TITLE
erode_edges_3d test fails stochastically

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-toolbox#25]
I've noticed a few time that erode_edges_3D doesn't always pass its random tests. For example: https://travis-ci.com/github/vanvalenlab/deepcell-toolbox/jobs/322850455

**Comment by ngreenwald** [comment]
Hmm, because I re-ran the test its now showing up as passing. 
But there appear to be some edge-cases that it's finding.

**Comment by ngreenwald** [comment]
Here's another one: https://travis-ci.com/github/vanvalenlab/deepcell-toolbox/jobs/323553650

**Comment by willgraf** [comment]
I can confirm this is definitely happening.
