### ISSUE TITLE
combine deep_watershed and deep_watershed_mibi

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-toolbox#51]
At some point we should combine deep_watershed and deep_watershed_mibi. 

This will require some breaking changes to applications and consumers, due to the different input data requirements.

**Comment by willgraf** [comment]
Was looking into this a bit and there seems to be one major difference: Using `peak_local_max` vs `h_maxima` to find watershed seeds.

Anecdotally it looks like `h_maxima` is much slower. @ngreenwald do you remember why `h_maxima` was chosen over `peak_local_max`?

**Comment by ngreenwald** [comment]
Dave said we should switch to it because it performs better

**Comment by vanvalen** [comment]
In my hands, the accuracy is higher in comparison to peak local max. It could be with hyperparameter optimization that you get the two to perform equally well.

**Comment by vanvalen** [comment]
I agree that they should be combined

**Comment by willgraf** [comment]
I'm finding that switching from `peak_local_max` to `h_maxima` drives up the computation time of `deep_watershed` from ~9s to ~41s, but I do not see any performance improvement (the metrics are exactly the same).

I'm testing with a PanopticNet model and the hela_s3 data on `deepcell.datasets`; 2880 batches of 128x128 images.

**Comment by ngreenwald** [comment]
There's not much ambiguity for cell centers in the nuclear culture data. I think the difference would likely only be apparent in the TissueNet data

**Comment by willgraf** [comment]
It does look like the addition of `watershed_line=0` in the `watershed` function and the `h_maxima` over `peak_local_max` does help quite a bit.

If only `h_maxima` were faster! It takes 20s to run the TissueNet test set  with `peak_local_max` and 120s with `h_maxima`

**Comment by ngreenwald** [comment]
You add a flag which controls which one we use? That way for easier stuff we could use the faster function. Not as satisfying though
