### ISSUE TITLE
Metrics package is slow

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-toolbox#68]
The metrics package is quite slow, and takes an order of magnitude longer to run than making the segmentation predictions themselves. This is likely because of scaling based on the pairwise interaction between the number of cells in each crop. Not pressing, but would be good to see if there's any optimization that can be done

**Comment by willgraf** [comment]
The metrics package also spams warnings during evaluation (using TensorFlow 2.x).
