### ISSUE TITLE
histogram normalization fails on constant images

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-toolbox#76]
The current histogram normalization function fails if an image of all constant values is passed in. Although unlikely, this could conceivably happen in real data if a small patch of a maxed out image is provided.

**Comment by willgraf** [comment]
As I'm looking into this in #84, I've learned some more about how `histogram_normalization` treats input files.

- Blank images (0-value constant) do not throw an error
- all -1 images also do not throw an error
- all 1-value images DO throw an error (`IndexError: index 49153 is out of bounds for axis 0 with size 16384`).
- constant values > 1 throw a different error (`ValueError: Images of type float must be between -1 and 1.`).
- constant values < -1 throw the same error as > 1.

There is a [documented issue](https://github.com/scikit-image/scikit-image/issues/4596) for this issue.

**Comment by ngreenwald** [comment]
What about checking if the input is constant valued, and if so, returning np.zeros_like() of the input image?
