### ISSUE TITLE
untile_image always uses same dtype as input image

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-toolbox#9]
the untile_image function always uses the same dtype as the input image. 

However, we usually store our mibi images as ints to save space. After inference, when I try and untile the model predictions, these 0-1 float values get converted to ints, and thus set to 0. 

I was thinking I'd submit a PR with dtype as an optional parameter to untile_image, that way it can be set if the user wants a different output dtype than input. 

If you think there's a better way to deal with this, let me know!

**Comment by willgraf** [comment]
I think that's a great idea!  Maybe have `dtype=None` as the default, and then do a quick default reassign `dtype = image.dtype if dtype is None else dtype`.

**Comment by ngreenwald** [comment]
Hah, I was thinking the same. Starting to figure out the lab's code style.

Can you add me as a collaborator?
