### ISSUE TITLE
Move multiplex utils into the Mesmer application?

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/deepcell-toolbox#96]
Should we migrate the contents of `multiplex_utils` to the `Mesmer` application?

We are renaming `multiplex` to `mesmer` everywhere, so this file should also get renamed. Since it really is only used on top of the application, maybe we should migrate the contents onto the application itself? Or as a function alongside the application?

This may also be a good time to look at #51.

**Comment by ngreenwald** [comment]
Initially we had this separate so that the kiosk-consumer could easily import it. Now that we're already importing the application, I agree that it makes more sense to have it there. 

What about the deep watershed function itself? In addition to combining, does it make sense to move that to the applications, or keep it here?

**Comment by willgraf** [comment]
I'm not as sure about `deep_watershed`. If it is shared across several Applications then maybe it should stay here?

Similarly, if we foresee the `multiplex_utils` being used by other applications/instances, it might make sense to leave it here since we are leaving other similar shared functions in `processing.py`.

**Comment by ngreenwald** [comment]
Right now the post-processing functions are super hardcoded for the specific Mesmer architecture. The pattern we've used here would be useful for future applications that have multiple output predictions, but that would require a refactor to make a more abstracted version which could then be modified by each of them.

**Comment by ngreenwald** [comment]
Let me know what you're thinking, happy to go with either approach, but I want to get this merged in today.

**Comment by willgraf** [comment]
I think we should move the multiplex utils to the same file as `Mesmer` application, but maybe not as a method of the class, just so that it can be used as the default value.

If possible I think we should branch off the current PR for these changes.

I think the `deep_watershed_mibi` changes might be too much for now, since it has downstream effects on other applications.
